export const REGISTRE = "REGISTRE";
export const REGISTRE_SUCCESS = "REGISTRE_SUCCESS";
export const REGISTRE_FAIL = "REGISTRE_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GETPROF = "GETPROF";
export const GETPROF_SUCCESS = "GETPROF_SUCCESS";
export const GETPROF_FAIL = "GETPROF_FAIL";

export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS";
export const GET_APPOINTMENT_FAIL = "GET_APPOINTMENT_FAIL";

export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";

export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_FAIL = "ADD_APPOINTMENT_FAIL";

export const LOG_OUT = "LOG_OUT";
